import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { getLogs, getStats, uploadCsv, type LogFilters } from './services/api'
import type { DashboardStats, LogsResponse, ProcessingSummary } from './types/monitoring'
import './styles.css'

const emptyStats: DashboardStats = { totalChecks: 0, successfulChecks: 0, failedChecks: 0, availabilityPercent: 0, averageLatencyMs: null, p95LatencyMs: null, perService: [], slaStatus: 'breached' }
const today = () => new Date().toISOString().slice(0, 10)
const percent = (n: number) => `${n.toFixed(2)}%`
const latency = (n: number | null) => n === null ? '—' : `${n.toFixed(0)} ms`
const when = (s: string) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(s))
const message = (e: unknown) => e instanceof Error ? e.message : 'Something went wrong.'

function UploadPanel({ onUploaded }: { onUploaded: (s: ProcessingSummary) => void }) {
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [drag, setDrag] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const choose = (f?: File) => { if (f) { setFile(f); setError('') } }
  const submit = async () => { if (!file) { setError('Choose a CSV file to upload.'); return }; if (!file.name.toLowerCase().endsWith('.csv')) { setError('Only .csv files are supported.'); return }; setLoading(true); setError(''); try { onUploaded(await uploadCsv(file)); setFile(null); if (input.current) input.current.value = '' } catch (e) { setError(message(e)) } finally { setLoading(false) } }
  return <section className="panel"><div className="section-heading"><div><p className="eyebrow">Data ingestion</p><h2>Upload monitoring data</h2></div><span className="file-hint">CSV · max 5 MB</span></div><div className={`dropzone ${drag ? 'is-dragging' : ''}`} onDragOver={e => { e.preventDefault(); setDrag(true) }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); choose(e.dataTransfer.files[0]) }}><div className="upload-icon">↑</div><div><strong>{file ? file.name : 'Drop your CSV here'}</strong><p>{file ? `${(file.size / 1024).toFixed(1)} KB ready to process` : 'or select a file from your computer'}</p></div><button className="button button-secondary" type="button" onClick={() => input.current?.click()}>Browse files</button><input ref={input} hidden type="file" accept=".csv,text/csv" onChange={e => choose(e.target.files?.[0])} /></div><div className="upload-footer"><span className="muted">Processed data is persisted for dashboard queries.</span><button className="button button-primary" disabled={loading} onClick={submit}>{loading ? <><span className="spinner" />Processing…</> : 'Upload & process'}</button></div>{error && <div className="alert alert-error" role="alert">{error}</div>}</section>
}
function Card({ label, value, note, tone }: { label: string; value: string; note?: string; tone?: string }) { return <div className="stat-card"><span>{label}</span><strong className={tone ?? ''}>{value}</strong>{note && <small>{note}</small>}</div> }
function Statistics({ stats, loading, error }: { stats: DashboardStats; loading: boolean; error: string }) {
  const [open, setOpen] = useState(true)
  return <section className="panel"><button className="collapse-toggle" onClick={() => setOpen(!open)} aria-expanded={open}><span><p className="eyebrow">At a glance</p><h2>Service health</h2></span><span className="chevron">{open ? '⌃' : '⌄'}</span></button>{open && <div className="stats-content">{error ? <div className="alert alert-error" role="alert">{error}</div> : <><div className="stat-grid"><Card label="Overall availability" value={percent(stats.availabilityPercent)} tone={stats.slaStatus === 'met' ? 'good' : 'bad'} note="Across all services" /><Card label="Total checks" value={stats.totalChecks.toLocaleString()} note={`${stats.successfulChecks.toLocaleString()} successful`} /><Card label="Failures" value={stats.failedChecks.toLocaleString()} tone={stats.failedChecks ? 'bad' : 'good'} note="Unhealthy checks" /><Card label="Average latency" value={latency(stats.averageLatencyMs)} /><Card label="P95 latency" value={latency(stats.p95LatencyMs)} /><Card label="SLA status" value={stats.slaStatus === 'met' ? 'Met' : 'Breached'} tone={stats.slaStatus === 'met' ? 'good' : 'bad'} note="Target ≥ 99.90%" /></div><div className="service-header"><h3>Per-service breakdown</h3><span className="status-pill met">{loading ? 'Refreshing…' : 'Live'}</span></div><div className="table-wrap"><table><thead><tr><th>Service</th><th>Availability</th><th>Checks</th><th>Failures</th><th>Avg latency</th><th>P95</th><th>SLA</th></tr></thead><tbody>{stats.perService.length ? stats.perService.map(s => <tr key={s.serviceId}><td><strong>{s.serviceName}</strong><small>{s.serviceId}</small></td><td><strong className={s.slaStatus === 'met' ? 'good' : 'bad'}>{percent(s.availabilityPercent)}</strong></td><td>{s.totalChecks.toLocaleString()}</td><td>{s.failedChecks.toLocaleString()}</td><td>{latency(s.averageLatencyMs)}</td><td>{latency(s.p95LatencyMs)}</td><td><span className={`status-pill ${s.slaStatus}`}>{s.slaStatus === 'met' ? 'Met' : 'Breached'}</span></td></tr>) : <tr><td colSpan={7} className="empty-cell">No statistics available yet.</td></tr>}</tbody></table></div></>}</div>}</section>
}
function Logs({ services, refreshKey }: { services: { id: string; name: string }[]; refreshKey: number }) {
  const [mode, setMode] = useState<'date' | 'range'>('date'); const [date, setDate] = useState(today()); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [service, setService] = useState(''); const [page, setPage] = useState(1); const [data, setData] = useState<LogsResponse>({ logs: [], pagination: { page: 1, limit: 50, total: 0, totalPages: 0 } }); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const filters = useMemo<LogFilters>(() => ({ ...(mode === 'date' ? { date } : { from, to }), ...(service ? { service } : {}), page, limit: 50 }), [mode, date, from, to, service, page])
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await getLogs(filters)) } catch (e) { setError(message(e)) } finally { setLoading(false) } }, [filters])
  useEffect(() => { load() }, [load, refreshKey]); const options = services.map(s => <option key={s.id} value={s.id}>{s.name}</option>)
  return <section className="panel logs-panel"><div className="section-heading"><div><p className="eyebrow">Detailed view</p><h2>Monitoring logs</h2></div><span className="record-count">{data.pagination.total.toLocaleString()} records</span></div><div className="filters" role="search"><div className="filter-mode"><button className={mode === 'date' ? 'active' : ''} onClick={() => { setMode('date'); setPage(1) }}>Single date</button><button className={mode === 'range' ? 'active' : ''} onClick={() => { setMode('range'); setPage(1) }}>Date range</button></div>{mode === 'date' ? <label>Date<input type="date" value={date} onChange={e => setDate(e.target.value)} /></label> : <><label>From<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>To<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label></>}<label>Service<select value={service} onChange={e => { setService(e.target.value); setPage(1) }}><option value="">All services</option>{options}</select></label><button className="button button-secondary apply-button" onClick={() => setPage(1)}>Apply filters</button></div>{error && <div className="alert alert-error" role="alert">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Timestamp</th><th>Service</th><th>Status</th><th>Latency</th><th>Agent</th><th>Region</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="empty-cell"><span className="spinner dark" />Loading logs…</td></tr> : data.logs.length ? data.logs.map(l => <tr key={`${l.datasetId}-${l.timestamp}-${l.serviceId}-${l.agent}`}><td>{when(l.timestamp)}</td><td><strong>{l.serviceName}</strong><small>{l.serviceId}</small></td><td><span className={`code-badge ${l.statusCode >= 200 && l.statusCode < 300 ? 'success' : 'failure'}`}>{l.statusCode}</span></td><td>{latency(l.latencyMs)}</td><td>{l.agent}</td><td>{l.region}</td></tr>) : <tr><td colSpan={6} className="empty-cell">No monitoring logs match these filters.</td></tr>}</tbody></table></div><div className="pagination"><span>Page {data.pagination.page} of {Math.max(data.pagination.totalPages, 1)}</span><div><button className="button button-secondary" disabled={page <= 1 || loading} onClick={() => setPage(p => p - 1)}>← Previous</button><button className="button button-secondary" disabled={page >= data.pagination.totalPages || loading} onClick={() => setPage(p => p + 1)}>Next →</button></div></div></section>
}
export default function App() {
  const [stats, setStats] = useState(emptyStats); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [refreshKey, setRefreshKey] = useState(0); const [summary, setSummary] = useState<ProcessingSummary | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(''); try { setStats(await getStats()) } catch (e) { setError(message(e)) } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load, refreshKey]); const services = stats.perService.map(s => ({ id: s.serviceId, name: s.serviceName }))
  return <main className="app-shell"><header className="topbar"><div className="brand-mark">S</div><div><h1>SLA Monitor</h1><p>Reliability command center</p></div><div className="topbar-meta"><span className="pulse" />System overview</div></header><div className="content"><UploadPanel onUploaded={s => { setSummary(s); setRefreshKey(k => k + 1) }} />{summary && <div className="alert alert-success" role="status"><strong>Import complete.</strong> {summary.insertedRows.toLocaleString()} rows added from {summary.totalRows.toLocaleString()} total records · {summary.rejectedRows} rejected · {summary.duplicates} duplicates.</div>}<Statistics stats={stats} loading={loading} error={error} /><Logs services={services} refreshKey={refreshKey} /></div><footer>UTC data · SLA target 99.90% · Monitoring dashboard</footer></main>
}
